config/routes.rb
Rails.application.routes.draw do
  resources :rosters

  resources :participants

  resources :locations

  resources :events

end

app/models/roster.rb
class Roster < ActiveRecord::Base
  belongs_to :event
  belongs_to :location
  belongs_to :participant
end

app/controllers/rosters_controller.rb
class RostersController < ApplicationController
  before_action :set_roster, only: [:show, :edit, :update, :destroy]

  # GET /rosters
  # GET /rosters.json
  def index
    @rosters = Roster.all
  end

  # GET /rosters/1
  # GET /rosters/1.json
  def show
  end

  # GET /rosters/new
  def new
    @roster = Roster.new
  end

  # GET /rosters/1/edit
  def edit
  end

  # POST /rosters
  # POST /rosters.json
  def create
    @roster = Roster.new(roster_params)

    respond_to do |format|
      if @roster.save
        format.html { redirect_to @roster, notice: 'Roster was successfully created.' }
        format.json { render :show, status: :created, location: @roster }
      else
        format.html { render :new }
        format.json { render json: @roster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rosters/1
  # PATCH/PUT /rosters/1.json
  def update
    respond_to do |format|
      if @roster.update(roster_params)
        format.html { redirect_to @roster, notice: 'Roster was successfully updated.' }
        format.json { render :show, status: :ok, location: @roster }
      else
        format.html { render :edit }
        format.json { render json: @roster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rosters/1
  # DELETE /rosters/1.json
  def destroy
    @roster.destroy
    respond_to do |format|
      format.html { redirect_to rosters_url, notice: 'Roster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roster
      @roster = Roster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roster_params
      params.require(:roster).permit(:event_id, :location_id, :participant_id)
    end
end

app/helpers/rosters_helper.rb
module RostersHelper
end

app/views/rosters/_form.html.erb
<%= form_for(@roster) do |f| %>
  <% if @roster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roster.errors.count, "error") %> prohibited this roster from being saved:</h2>

      <ul>
      <% @roster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.text_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.text_field :location_id %>
  </div>
  <div class="field">
    <%= f.label :participant_id %><br>
    <%= f.text_field :participant_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rosters/edit.html.erb
<h1>Editing roster</h1>

<%= render 'form' %>

<%= link_to 'Show', @roster %> |
<%= link_to 'Back', rosters_path %>

app/views/rosters/index.html.erb
<h1>Listing rosters</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Location</th>
      <th>Participant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rosters.each do |roster| %>
      <tr>
        <td><%= roster.event %></td>
        <td><%= roster.location %></td>
        <td><%= roster.participant %></td>
        <td><%= link_to 'Show', roster %></td>
        <td><%= link_to 'Edit', edit_roster_path(roster) %></td>
        <td><%= link_to 'Destroy', roster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roster', new_roster_path %>

app/views/rosters/new.html.erb
<h1>New roster</h1>

<%= render 'form' %>

<%= link_to 'Back', rosters_path %>

app/views/rosters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @roster.event %>
</p>

<p>
  <strong>Location:</strong>
  <%= @roster.location %>
</p>

<p>
  <strong>Participant:</strong>
  <%= @roster.participant %>
</p>

<%= link_to 'Edit', edit_roster_path(@roster) %> |
<%= link_to 'Back', rosters_path %>